source 'https://rubygems.org'

gem "eventmachine"
gem "vcap_logging"
gem "yajl-ruby"
gem "vcap-concurrency", :git => "https://github.com/cloudfoundry/vcap-concurrency.git"
gem "cf-message-bus", :git => "https://github.com/cloudfoundry/cf-message-bus.git"

group :development, :test do
  gem "rspec"
end
